const deck = [],
	dealerCards = [],
	playerCards = [],
	dealerHand = document.querySelector(".container_dealer-hand"),
	playerHand = document.querySelector(".container_player-hand"),
	hitButton = document.querySelector(".hit"),
	loseDialog = document.querySelector(".lose_dialog"),
	losetextDialog = document.querySelector(".lose_dialog > h3"),
	[btnCloseLose, btnCloseWin] = document.querySelectorAll(".btn-close_dialog"),
	btnStand = document.querySelector(".stand"),
	winDialog = document.querySelector(".win_dialog"),
	winTextDialog = document.querySelector(".win_dialog > h3"),
	playerPoints = [0],
	dealerPoints = [0];

export {
	playerPoints,
	dealerPoints,
	deck,
	dealerCards,
	playerCards,
	dealerHand,
	playerHand,
	hitButton,
	loseDialog,
	losetextDialog,
	btnCloseLose,
	btnCloseWin,
	btnStand,
	winDialog,
	winTextDialog,
};
